In [1]:
import pandas as pd
import re  # This imports the regular expressions module
%matplotlib inline

DATA_FOLDER = 'Data/'

CHARACTER_METADATA_DATASET = DATA_FOLDER+"character.metadata.tsv"
MOVIE_METADATA_DATASET = DATA_FOLDER+"movie.metadata.tsv"

In [2]:
column_names_character = [
    'Wikipedia movie ID',
    'Freebase movie ID',
    'Movie release date',
    'Character name',
    'Actor date of birth',
    'Actor gender',
    'Actor height (in meters)',
    'Actor ethnicity (Freebase ID)',
    'Actor name',
    'Actor age at movie release',
    'Freebase character/actor map ID',
    'Freebase character ID',
    'Freebase actor ID'
]

column_names_movie = [
    'Wikipedia movie ID',
    'Freebase movie ID',
    'Movie name',
    'Movie release date',
    'Movie box office revenue',
    'Movie runtime',
    'Movie languages',
    'Movie countries',
    'Movie genres'
]
df_character=pd.read_csv(CHARACTER_METADATA_DATASET, sep='\t', names = column_names_character)
df_movie=pd.read_csv(MOVIE_METADATA_DATASET, sep='\t', names = column_names_movie)

In [3]:
df_character.head(10)

,Wikipedia movie ID,Freebase movie ID,Movie release date,Character name,Actor date of birth,Actor gender,Actor height (in meters),Actor ethnicity (Freebase ID),Actor name,Actor age at movie release,Freebase character/actor map ID,Freebase character ID,Freebase actor ID
0,975900,/m/03vyhn,2001-08-24,Akooshay,1958-08-26,F,1.620,NaN,Wanda De Jesus,42.0,/m/0bgchxw,/m/0bgcj3x,/m/03wcfv7
1,975900,/m/03vyhn,2001-08-24,Lieutenant Melanie Ballard,1974-08-15,F,1.780,/m/044038p,Natasha Henstridge,27.0,/m/0jys3m,/m/0bgchn4,/m/0346l4
2,975900,/m/03vyhn,2001-08-24,Desolation Williams,1969-06-15,M,1.727,/m/0x67,Ice Cube,32.0,/m/0jys3g,/m/0bgchn_,/m/01vw26l
3,975900,/m/03vyhn,2001-08-24,Sgt Jericho Butler,1967-09-12,M,1.750,NaN,Jason Statham,33.0,/m/02vchl6,/m/0bgchnq,/m/034hyc
4,975900,/m/03vyhn,2001-08-24,Bashira Kincaid,1977-09-25,F,1.650,NaN,Clea DuVall,23.0,/m/02vbb3r,/m/0bgchp9,/m/01y9xg
5,975900,/m/03vyhn,2001-08-24,Commander Helena Braddock,1949-05-26,F,1.727,/m/0x67,Pam Grier,52.0,/m/02vdcfp,/m/0bgchnd,/m/0418ft
6,975900,/m/03vyhn,2001-08-24,Whitlock,1945-08-02,F,1.753,NaN,Joanna Cassidy,56.0,/m/02vd6kw,/m/0bgchmx,/m/06lj1m
7,975900,/m/03vyhn,2001-08-24,Big Daddy Mars,NaN,M,NaN,NaN,Richard Cetrone,NaN,/m/0bgchsy,/m/0bgcht0,/m/0bgcht7
8,975900,/m/03vyhn,2001-08-24,Michael Descanso,1971-03-20,M,1.892,NaN,Liam Waite,30.0,/m/03jqhb0,/m/0bgchs4,/m/0ks8b0
9,975900,/m/03vyhn,2001-08-24,Uno,NaN,M,NaN,NaN,Duane Davis,NaN,/m/0bgchtj,/m/0bgchtm,/m/03nrwdy

In [4]:
df_character.dtypes
df_character.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450669 entries, 0 to 450668
Data columns (total 13 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Wikipedia movie ID               450669 non-null  int64
 1   Freebase movie ID                450669 non-null  object
 2   Movie release date               440674 non-null  object
 3   Character name                   192794 non-null  object
 4   Actor date of birth              344524 non-null  object
 5   Actor gender                     405060 non-null  object
 6   Actor height (in meters)         154824 non-null  float64
 7   Actor ethnicity (Freebase ID)    106058 non-null  object
 8   Actor name                       449441 non-null  object
 9   Actor age at movie release       292556 non-null  float64
 10  Freebase character/actor map ID  450669 non-null  object
 11  Freebase character ID            192804 non-null  object
 12  Freebase actor ID                449854 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 44.7+ MB

In [5]:
df_movie.head(10)

,Wikipedia movie ID,Freebase movie ID,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages,Movie countries,Movie genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
5,13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,"{""/m/06ppq"": ""Silent film"", ""/m/02h40lc"": ""Eng...","{""/m/09c7w0"": ""United States of America""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen..."
6,18998739,/m/04jcqvw,The Sorcerer's Apprentice,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0hzlz"": ""South Africa""}","{""/m/0hqxf"": ""Family Film"", ""/m/01hmnh"": ""Fant..."
7,10408933,/m/02qc0j7,Alexander's Ragtime Band,1938-08-16,3600000.0,106.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/04t36"": ""Musical"", ""/m/01z4y"": ""Comedy"", ..."
8,9997961,/m/06_y2j7,Contigo y aquí,1974,NaN,NaN,"{""/m/06nm1"": ""Spanish Language""}","{""/m/0jgd"": ""Argentina""}","{""/m/04t36"": ""Musical"", ""/m/07s9rl0"": ""Drama"",..."
9,2345652,/m/075f66,City of the Dead,1960,NaN,76.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/03npn"": ""Horror"", ""/m/0fdjb"": ""Supernatur..."

In [6]:
df_movie.dtypes
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81741 entries, 0 to 81740
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Wikipedia movie ID        81741 non-null  int64
 1   Freebase movie ID         81741 non-null  object
 2   Movie name                81741 non-null  object
 3   Movie release date        74839 non-null  object
 4   Movie box office revenue  8401 non-null   float64
 5   Movie runtime             61291 non-null  float64
 6   Movie languages           81741 non-null  object
 7   Movie countries           81741 non-null  object
 8   Movie genres              81741 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 5.6+ MB

In [7]:
df_movie_treated = df_movie.copy()


def cleaner(value):
    # Find all occurrences of languages between quotes after the colon
    matches = re.findall(r'":\s*"([^"]+)"', value) #extracts values after a ":" that is in between "'s. 
    if matches:
        # Return all matched languages as a comma-separated string
        return ', '.join(matches)
    return value
    
def remove_unicode_escapes(value):
    # Use a regex to remove any Unicode escape sequences (\udxxx\udxxx)
    return re.sub(r'\\ud[0-9a-fA-F]{3}', '', value)
    
df_movie_treated['Movie languages'] = df_movie_treated['Movie languages'].apply(cleaner)
df_movie_treated['Movie countries'] = df_movie_treated['Movie countries'].apply(cleaner)
df_movie_treated['Movie genres'] = df_movie_treated['Movie genres'].apply(cleaner)
df_movie_treated['Movie languages'] = df_movie_treated['Movie languages'].apply(remove_unicode_escapes)

df_movie_treated = df_movie_treated.set_index(['Wikipedia movie ID', 'Freebase movie ID'])

In [8]:
df_movie_treated.head(10)

,,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages,Movie countries,Movie genres
Wikipedia movie ID,Freebase movie ID,,,,,,,
975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,English Language,United States of America,"Thriller, Science Fiction, Horror, Adventure, ..."
3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,English Language,United States of America,"Mystery, Biographical film, Drama, Crime Drama"
28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,Norwegian Language,Norway,"Crime Fiction, Drama"
9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,English Language,United Kingdom,"Thriller, Erotic thriller, Psychological thriller"
261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,German Language,Germany,Drama
13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,"Silent film, English Language",United States of America,"Short Film, Silent film, Indie, Black-and-whit..."
18998739,/m/04jcqvw,The Sorcerer's Apprentice,2002,NaN,86.0,English Language,South Africa,"Family Film, Fantasy, Adventure, World cinema"
10408933,/m/02qc0j7,Alexander's Ragtime Band,1938-08-16,3600000.0,106.0,English Language,United States of America,"Musical, Comedy, Black-and-white"
9997961,/m/06_y2j7,Contigo y aquí,1974,NaN,NaN,Spanish Language,Argentina,"Musical, Drama, Comedy"
2345652,/m/075f66,City of the Dead,1960,NaN,76.0,English Language,United Kingdom,"Horror, Supernatural"

In [9]:
languages = df_movie_treated.groupby('Movie languages').size()
print(languages)

Movie languages
, German Language                                                                                          1
Aboriginal Malay languages, English Language                                                               1
Aceh Language, Dutch Language, Indonesian Language                                                         1
Afrikaans Language                                                                                         5
Afrikaans Language, English Language                                                                      16
                                                                                                       ...
Zulu Language                                                                                              1
Zulu Language, English Language                                                                            8
Zulu Language, Hebrew Language, English Language                                                           1
Zulu Language, Xhosa Language, Afrikaans Language, Sotho language, English Language, Chewa language        1
{}                                                                                                     13866
Length: 1817, dtype: int64

In [10]:
countries = df_movie_treated.groupby('Movie countries').size()
print(countries)

Movie countries
Afghanistan                                             2
Afghanistan, Canada, India, Portugal                    1
Afghanistan, India                                      2
Afghanistan, Ireland, Japan                             1
Afghanistan, Pakistan                                   1
                                                     ...
Yugoslavia, West Germany, United Kingdom, Germany       1
Zambia, Australia, Sweden                               1
Zimbabwe                                                3
Zimbabwe, Germany                                       1
{}                                                   8154
Length: 2124, dtype: int64

In [11]:
genres = df_movie_treated.groupby('Movie genres').size()
print(genres)

Movie genres
Absurdism, Buddy film, Comedy, Slapstick                                        1
Absurdism, Comedy-drama, Satire, Drama, Comedy, Black comedy, Tragicomedy       1
Absurdism, Drama, Comedy, Indie                                                 1
Absurdism, Indie, Comedy, Slapstick                                             1
Absurdism, Musical comedy, Satire, Adventure Comedy, Comedy, Action, Spy        1
                                                                             ...
Zombie Film, Science Fiction, Horror, Sci-Fi Horror                             1
Zombie Film, Science Fiction, Horror, World cinema                              2
Zombie Film, Silent film, Drama, Indie, Black-and-white                         1
Zombie Film, Thriller, Horror, Supernatural                                     1
{}                                                                           2294
Length: 23817, dtype: int64

In [12]:
df_movie_treated['Movie languages'] = df_movie_treated['Movie languages'].apply(lambda x: x.split(', '))
df_movie_treated['Movie countries'] = df_movie_treated['Movie countries'].apply(lambda x: x.split(', '))
df_movie_treated['Movie genres'] = df_movie_treated['Movie genres'].apply(lambda x: x.split(', '))

In [13]:
all_countries = sum(df_movie_treated['Movie countries'], [])
unique_countries = list(set(all_countries))
print(unique_countries)

all_languages = sum(df_movie_treated['Movie languages'], [])
unique_languages = list(set(all_languages))
print(unique_languages)

all_genres = sum(df_movie_treated['Movie genres'], [])
unique_genres = list(set(all_genres))
print(unique_genres)

['German Language', 'Japan', 'Indonesia', 'Montenegro', 'Guinea-Bissau', 'Brazil', 'China', 'Ukrainian SSR', 'Armenia', 'Afghanistan', 'Iran', 'Jamaica', 'Mongolia', 'Iraqi Kurdistan', 'Uzbekistan', 'Czechoslovakia', 'Slovenia', 'Turkey', 'Kenya', 'Morocco', 'Kuwait', 'Estonia', '{}', 'Iraq', 'Malayalam Language', 'Malaysia', 'Nepal', 'Romania', 'United Arab Emirates', 'Haiti', 'South Africa', 'Argentina', 'Hong Kong', 'Poland', 'Nazi Germany', 'Nigeria', 'Canada', 'Korea', 'Bangladesh', 'Zimbabwe', 'Portugal', 'Zambia', 'Federal Republic of Yugoslavia', 'United Kingdom', 'Finland', 'Burma', 'Ukranian SSR', 'Burkina Faso', 'Ethiopia', 'West Germany', 'Puerto Rico', 'Venezuela', 'Sri Lanka', 'Netherlands', 'Wales', 'Australia', 'Congo', 'United States of America', 'Scotland', 'Iceland', 'Bulgaria', 'Socialist Federal Republic of Yugoslavia', 'Denmark', 'Jordan', 'Cameroon', 'Soviet occupation zone', 'Ireland', 'Bolivia', 'Singapore', 'Italy', 'Spain', 'Russia', 'Uzbek SSR', 'Lebanon', 'Serbia and Montenegro', 'Palestinian territories', 'Bahrain', 'Libya', 'Slovak Republic', 'Chile', 'Cambodia', 'Monaco', 'Slovakia', 'Uruguay', 'Israel', 'Colombia', 'India', 'Senegal', 'Norway', 'Costa Rica', 'Sweden', 'Serbia', 'Cyprus', 'Aruba', 'Turkmenistan', 'Vietnam', 'Crime', 'Mandatory Palestine', 'Belgium', 'Republic of Macedonia', 'Algeria', 'Hungary', 'Northern Ireland', 'France', 'Ukraine', 'German Democratic Republic', 'Philippines', 'Macau', 'Austria', 'Switzerland', 'Qatar', 'Georgian SSR', 'Mali', 'Georgia', 'Peru', 'Isle of Man', 'Malta', 'New Zealand', 'Bahamas', 'Thailand', 'Democratic Republic of the Congo', 'Bhutan', 'Kingdom of Italy', 'Cuba', 'Greece', 'Yugoslavia', 'Palestinian Territories', 'Soviet Union', 'Azerbaijan', 'Pakistan', 'Albania', 'Taiwan', 'Egypt', 'England', 'Guinea', 'Republic of China', 'Bosnia and Herzegovina', 'Weimar Republic', 'Mexico', 'South Korea', 'Luxembourg', 'Tunisia', 'Germany', 'Kingdom of Great Britain', 'Croatia', 'Czech Republic', 'Lithuania', 'Panama']
['German Language', '', 'Hausa Language', 'Hawaiian language', 'Japan', 'French Language', 'Azerbaijani language', 'Chinese language', 'Old English language', 'Tibetan languages', 'Friulian Language', 'Northeastern Language', 'Apache', 'Hazaragi Language', 'Mandarin Chinese', 'Assyrian language', 'Plautdietsch Language', 'Kriolu', 'Indian English', 'Standard Cantonese', 'Silent film', 'Venetian Language', 'Tulu Language', 'Haryanvi Language', 'Egyptian Arabic', '{}', 'Malayalam Language', 'American Sign Language', 'Southwestern Mandarin', 'Croatian language', 'Danish Language', 'Taiwanese', 'Australian Aboriginal Pidgin English', 'Serbian language', 'Punjabi language', 'Sumerian', 'Uzbek language', 'Welsh Language', 'Egyptian', 'Rajasthani language', 'Deutsch', 'Papiamento language', 'M\\u0101ori language', 'Vietnamese Language', 'South African English', 'French Sign Language', 'Standard Mandarin', 'Cree language', 'Tamil Language', 'Algonquin Language', 'Shanxi', 'Lithuanian language', 'Sanskrit Language', 'Telugu language', 'Sinhala Language', 'Czech Language', 'Cebuano language', 'Aramaic language', 'Aboriginal Malay languages', 'Assyrian Neo-Aramaic Language', 'Tzotzil language', 'Central Language', 'Chadian Arabic', 'Dzongkha Language', 'Maasai Language', 'Classical Arabic', 'Dutch Language', 'Jamaican Creole English Language', 'Macedonian Language', 'Navajo Language', 'Akan Language', 'Russian Language', 'Thai', 'Yolngu Matha', 'Palawa kani', 'Flemish language', 'Ukrainian Language', 'Inuktitut', 'Mongolian language', 'Italian Language', 'Shanghainese', 'Thai Language', 'Brazilian Portuguese', 'Scanian Language', 'Filipino language', 'Min Nan', 'Awadhi Language', 'Korean Sign Language', 'Cantonese', 'Kurdish language', 'Japanese Language', 'American English', 'Somali Language', 'Khmer', 'Slovenian language', 'Ancient', 'Armenian Language', 'Crow Language', 'Pawnee Language', 'Klingon language', 'Latin Language', 'Judeo-Georgian Language', 'Hebrew Language', 'Kannada Language', 'Corsican Language', 'Gumatj Language', 'Bosnian language', 'Sicilian Language', 'Galician Language', 'Serbo-Croatian', 'Cheyenne Language', 'Sioux language', 'Kinyarwanda language', 'Jinyu Language', 'Banyumasan language', 'Kuna language', 'Bulgarian Language', 'Mende Language', 'Maya', 'Tagalog language', 'Norwegian Language', 'Georgian Language', 'Chinese', 'Estonian Language', 'Persian Language', 'Hungarian language', 'Guanzhong Hua', 'Korean Language', 'Assamese Language', 'Spanish Language', 'Tok Pisin Language', 'Hakka Language', 'Finnish Language', 'Slovak Language', 'Romani language', 'Swahili Language', 'Swiss German Language', 'Wolof Language', 'Hungary', 'France', 'Hindi Language', 'Maninka language', 'Western Language', 'Saami', 'Chechen Language', 'Amharic Language', 'Chhattisgarhi Language', 'Gaelic', 'Romanian Language', 'Burmese Language', 'Bengali Language', 'Sunda Language', 'Hopi Language', 'Teochew', 'Yiddish Language', 'Hmong language', 'Nahuatl languages', 'Yucat\\u00e1n Language', 'Osetin Language', 'Hinglish', 'Bhojpuri Language', 'Fulfulde', 'Catalan language', 'Australian English', 'Malay Language', 'Hiligaynon language', 'Frisian', 'German', 'Turkish Language', 'Luxembourgish language', 'Albanian language', 'Mohawk Language', 'Portuguese Language', 'Polish Language', 'Irish', 'Sotho language', 'Dari', 'Krio Language', 'Adamawa Language', 'Indonesian Language', 'Hainanese', 'North Language', 'Zulu Language', 'Standard Tibetan', 'Oriya Language', 'Swedish Language', 'Italian', 'Arabic Language', 'Marathi Language', 'Quechua', 'Aceh Language', 'Scottish Gaelic language', 'Gujarati Language', 'Urdu Language', 'Sami languages', 'Bambara language', 'English Language', 'Tamang language', 'Hariyani', 'Hokkien', 'Belarusian language', 'Farsi', 'Chewa language', 'Pashto language', 'Hindustani language', 'Nepali Language', 'Greek Language', 'Napoletano-Calabrese Language', 'Icelandic Language', 'Esperanto Language', 'Ancient Greek', 'Xhosa Language', 'Khmer language', 'Fula language', 'Afrikaans Language', 'Picard Language']
['Gender Issues', 'Bengali Cinema', 'Cult', 'Kafkaesque', 'Avant-garde', 'Fairy tale', 'Drama', 'Plague', 'Cavalry Film', '{}', 'Malayalam Cinema', 'Historical Epic', 'Chinese Movies', 'Hardcore pornography', 'Christmas movie', 'Holiday Film', 'Finance & Investing', 'Animation', 'Road movie', 'Expressionism', 'Documentary', 'Baseball', 'Filmed Play', 'War film', 'Japanese Movies', 'Period Horror', 'Domestic Comedy', 'Social issues', 'Medical fiction', 'Docudrama', 'Creature Film', 'Space opera', 'Backstage Musical', 'Biographical film', 'Linguistics', 'Sword and Sandal', 'Horror', 'Film \\u00e0 clef', 'Parkour in popular culture', 'Feminist Film', 'Concert film', 'Auto racing', 'Comedy', "Children's/Family", 'Black comedy', 'Ensemble Film', 'Sex comedy', 'Tragedy', 'Ninja movie', 'Epic', 'Hybrid Western', 'Singing cowboy', 'Fictional film', 'Splatter film', 'Tragicomedy', 'Psychological horror', 'Musical Drama', 'Apocalyptic and post-apocalyptic fiction', 'Alien invasion', 'Buddy film', 'Roadshow theatrical release', 'Gay Interest', 'Neo-noir', 'Fantasy Comedy', 'Film & Television History', 'C-Movie', 'Softcore Porn', 'Biker Film', 'Mockumentary', 'Crime Fiction', 'Epic Western', 'Filipino Movies', 'Kitchen sink realism', 'Hip hop movies', 'Inspirational Drama', 'Political satire', 'Hagiography', 'Courtroom Drama', 'Computers', 'Heaven-Can-Wait Fantasies', 'School story', 'Workplace Comedy', 'Haunted House Film', 'Stand-up comedy', 'Black-and-white', 'Female buddy film', 'Albino bias', 'Psycho-biddy', 'Star vehicle', 'Camp', 'Fantasy', 'Revisionist Western', 'War effort', 'Biopic [feature]', 'New Hollywood', 'Political cinema', 'Jukebox musical', 'Political drama', 'Action Comedy', 'Adult', 'Homoeroticism', 'Educational', 'Fantasy Adventure', 'Therimin music', 'Remake', 'Live action', 'Cyberpunk', 'Thriller', 'Prison film', 'History', 'Road-Horror', 'Political Documetary', 'Samurai cinema', 'Boxing', 'Time travel', 'Music', 'Martial Arts Film', 'Ealing Comedies', 'Animated cartoon', "Children's Fantasy", 'Combat Films', 'Addiction Drama', 'Indie', 'Superhero', 'Travel', 'Romantic thriller', 'Tokusatsu', 'Costume Adventure', 'Private military company', 'Anti-war', 'Pinku eiga', 'Sci-Fi Thriller', 'Courtroom Comedy', 'Horror Comedy', 'Coming of age', 'Short Film', 'Rockumentary', 'Supermarionation', 'Pornographic movie', 'Biography', 'Detective fiction', 'Slice of life story', 'Roadshow/Carny', 'Action Thrillers', 'Indian Western', 'Feature film', 'Chick flick', 'Clay animation', 'Beach Film', 'Race movie', 'Slasher', 'Sexploitation', 'B-Western', 'Superhero movie', 'Sci-Fi Horror', 'Illnesses & Disabilities', 'Z movie', 'Instrumental Music', 'Political thriller', 'Goat gland', 'Comedy horror', 'Law & Crime', 'Historical Documentaries', 'Silhouette animation', 'Historical drama', 'Northern', 'Musical', 'Animals', 'Point of view shot', 'Sword and sorcery', 'Nuclear warfare', 'Sports', 'Breakdance', 'Dance', 'Bruceploitation', 'Doomsday film', 'Buddy Picture', 'Statutory rape', 'Bollywood', 'Outlaw biker film', 'Gross-out film', 'Romantic fantasy', 'Demonic child', 'Teen', 'Religious Film', 'Essay Film', 'Women in prison films', 'Media Satire', 'Science Fiction', "Children's", 'Gay', 'Family Film', 'Costume drama', 'Film adaptation', 'Airplanes and airports', 'Marriage Drama', 'World History', 'Gulf War', 'Western', 'Sci-Fi Adventure', 'Silent film', 'Monster movie', 'Anthology', 'New Queer Cinema', 'Alien Film', 'Melodrama', 'Archives and records', 'Dystopia', 'Dogme 95', 'Erotica', 'Beach Party film', 'Space western', 'Humour', 'Chase Movie', 'Romance Film', 'Juvenile Delinquency Film', 'Journalism', 'Vampire movies', 'Film', "Children's Issues", 'Comedy film', 'Crime Comedy', 'Glamorized Spy Film', 'Gothic Film', 'Caper story', 'Latino', 'Gross out', 'Slapstick', 'Wuxia', 'Family Drama', 'Mumblecore', 'Adventure', 'Social problem film', 'British New Wave', 'Language & Literature', 'Nature', 'Family-Oriented Adventure', 'Erotic Drama', 'Spaghetti Western', 'Stoner film', 'Existentialism', 'Supernatural', 'Comedy of Errors', 'Exploitation', 'Crime', 'Spy', 'Jungle Film', 'British Empire Film', 'Legal drama', 'Culture & Society', 'Comdedy', 'Outlaw', 'Sci Fi Pictures original films', 'Interpersonal Relationships', 'Environmental Science', 'Werewolf fiction', 'Zombie Film', 'B-movie', 'Steampunk', 'Foreign legion', 'Gay Themed', 'Animated Musical', 'Blaxploitation', 'Health & Fitness', 'Computer Animation', 'Master Criminal Films', 'Movie serial', 'Natural disaster', 'Film noir', 'Disaster', 'Action/Adventure', 'Inventions & Innovations', 'Animal Picture', 'Education', 'Romantic drama', 'Erotic thriller', 'Mystery', 'Bloopers & Candid Camera', 'Family & Personal Relationships', 'Mythological Fantasy', 'Gangster Film', 'Anti-war film', 'Prison escape', 'Screwball comedy', 'Punk rock', 'Sword and sorcery films', 'Neorealism', 'Filipino', 'Escape Film', 'Movies About Gladiators', 'Fan film', 'LGBT', 'Comedy Thriller', 'Anthropology', 'Tamil cinema', 'Propaganda film', 'Giallo', 'Future noir', 'Americana', 'Monster', 'Parody', 'Absurdism', 'Satire', 'Science fiction Western', 'Tollywood', 'Buddy cop', 'Operetta', 'Libraries and librarians', 'Period piece', 'Psychological thriller', 'Art film', 'Comedy of manners', "Children's Entertainment", 'Crime Drama', 'Revisionist Fairy Tale', 'Pre-Code', 'Early Black Cinema', 'Graphic & Applied Arts', 'Comedy Western', 'Comedy-drama', 'World cinema', 'Film-Opera', 'Cold War', 'Pornography', 'The Netherlands in World War II', 'Sponsored film', 'Business', 'Suspense', 'Extreme Sports', 'Heist', 'Surrealism', 'Whodunit', 'Horse racing', 'Coming-of-age film', 'Crime Thriller', 'News', 'Romantic comedy', 'Conspiracy fiction', 'Reboot', 'Costume Horror', 'Christian film', 'Adventure Comedy', 'Musical comedy', 'Natural horror films', 'Czechoslovak New Wave', 'Swashbuckler films', 'Experimental film', 'Historical fiction', 'Television movie', 'Acid western', 'Stop motion', 'Fantasy Drama', 'Prison', 'Archaeology', 'Heavenly Comedy', 'Gay pornography', 'Mondo film', 'Detective', 'Anime', 'Action', 'Childhood Drama', 'Revenge', 'Media Studies', 'Patriotic film']

In [14]:
print(df_movie_treated['Movie release date'].isnull().sum())
df_movie_treated = df_movie_treated.dropna(subset=['Movie release date'])
print(df_movie_treated['Movie release date'].isnull().sum())

6902
0

In [15]:
def parse_date(date_str):
    # Check if the date has only 4 characters (year-only entry)
    if len(date_str) == 4:
        # Convert year-only to a complete date (e.g., January 1st of that year)
        return pd.to_datetime(date_str + '-01-01', format='%Y-%m-%d')
    else:
        # Handle full dates as is (YYYY-MM-DD)
        return pd.to_datetime(date_str, format='%Y-%m-%d', errors='coerce')

df_movie_treated['Movie release date'] = df_movie_treated['Movie release date'].apply(parse_date)
df_movie_treated.head(10)

,,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages,Movie countries,Movie genres
Wikipedia movie ID,Freebase movie ID,,,,,,,
975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,[English Language],[United States of America],"[Thriller, Science Fiction, Horror, Adventure,..."
3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,[English Language],[United States of America],"[Mystery, Biographical film, Drama, Crime Drama]"
28463795,/m/0crgdbh,Brun bitter,1988-01-01,NaN,83.0,[Norwegian Language],[Norway],"[Crime Fiction, Drama]"
9363483,/m/0285_cd,White Of The Eye,1987-01-01,NaN,110.0,[English Language],[United Kingdom],"[Thriller, Erotic thriller, Psychological thri..."
261236,/m/01mrr1,A Woman in Flames,1983-01-01,NaN,106.0,[German Language],[Germany],[Drama]
13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,"[Silent film, English Language]",[United States of America],"[Short Film, Silent film, Indie, Black-and-whi..."
18998739,/m/04jcqvw,The Sorcerer's Apprentice,2002-01-01,NaN,86.0,[English Language],[South Africa],"[Family Film, Fantasy, Adventure, World cinema]"
10408933,/m/02qc0j7,Alexander's Ragtime Band,1938-08-16,3600000.0,106.0,[English Language],[United States of America],"[Musical, Comedy, Black-and-white]"
9997961,/m/06_y2j7,Contigo y aquí,1974-01-01,NaN,NaN,[Spanish Language],[Argentina],"[Musical, Drama, Comedy]"
2345652,/m/075f66,City of the Dead,1960-01-01,NaN,76.0,[English Language],[United Kingdom],"[Horror, Supernatural]"

In [16]:
inflation_data = {
    1914: 1.3, 1915: 0.9, 1916: 7.7, 1917: 17.8, 1918: 17.3, 
    1919: 15.2, 1920: 15.6, 1921: -10.9, 1922: -6.2, 1923: 1.8, 
    1924: 0.4, 1925: 2.4, 1926: 0.9, 1927: -1.9, 1928: -1.2, 
    1929: 0.0, 1930: -2.7, 1931: -8.9, 1932: -10.3, 1933: -5.2, 
    1934: 3.5, 1935: 2.6, 1936: 1.0, 1937: 3.7, 1938: -2.0, 
    1939: -1.3, 1940: 0.7, 1941: 5.1, 1942: 10.9, 1943: 6.0, 
    1944: 1.6, 1945: 2.3, 1946: 8.5, 1947: 14.4, 1948: 7.7, 
    1949: -1.0, 1950: 1.1, 1951: 7.9, 1952: 2.3, 1953: 0.8, 
    1954: 0.3, 1955: -0.3, 1956: 1.5, 1957: 3.3, 1958: 2.7, 
    1959: 1.08, 1960: 1.5, 1961: 1.1, 1962: 1.2, 1963: 1.2, 
    1964: 1.3, 1965: 1.6, 1966: 3.0, 1967: 2.8, 1968: 4.3, 
    1969: 5.5, 1970: 5.8, 1971: 4.3, 1972: 3.3, 1973: 6.2, 
    1974: 11.1, 1975: 9.1, 1976: 5.7, 1977: 6.5, 1978: 7.6, 
    1979: 11.3, 1980: 13.5, 1981: 10.3, 1982: 6.1, 1983: 3.2, 
    1984: 4.3, 1985: 3.5, 1986: 1.9, 1987: 3.7, 1988: 4.1, 
    1989: 4.8, 1990: 5.4, 1991: 4.2, 1992: 3.0, 1993: 3.0, 
    1994: 2.6, 1995: 2.8, 1996: 2.9, 1997: 2.3, 1998: 1.6, 
    1999: 2.2, 2000: 3.4, 2001: 2.8, 2002: 1.6, 2003: 2.3, 
    2004: 2.7, 2005: 3.4, 2006: 3.2, 2007: 2.9, 2008: 3.8, 
    2009: -0.4, 2010: 1.6, 2011: 3.2, 2012: 2.1, 2013: 1.5, 
    2014: 1.6, 2015: 0.1, 2016: 1.3, 2017: 2.1, 2018: 2.4, 
    2019: 1.8, 2020: 1.2, 2021: 4.7, 2022: 8.0, 2023: 4.1, 2024: 3.2
}

#source : minesota website


def adjust_for_inflation(year, amount, inflation_data):
    """
    Adjusts the given amount from the provided year to 2024 based on annual inflation rates.

    Parameters:
    year (int): The starting year.
    amount (float): The amount to be adjusted.
    inflation_data (dict): A dictionary with years as keys and inflation rates as values.

    Returns:
    float: The inflation-adjusted amount for 2024.
    """
    # Initialize the adjusted amount
    adjusted_value = amount
    
    # Loop through each year from the given year to 2024
    for y in range(year, 2024):
        if y in inflation_data:
            inflation_rate = inflation_data[y]
            # Adjust for inflation for each year
            adjusted_value *= (1 + inflation_rate / 100)
        else:
            print(f"Warning: No inflation data available for year {y}. Assuming 0% inflation.")
    
    return adjusted_value
# Iterate over the rows using iloc and range(len(df))
for i in range(len(df_movie_treated)):
    # Check if both the release date and box office revenue are not NaN
    if pd.notna(df_movie_treated.iloc[i]['Movie release date']) and pd.notna(df_movie_treated.iloc[i]['Movie box office revenue']):
        # Extract the year from the release date
        release_year = df_movie_treated.iloc[i]['Movie release date'].year
        
        # Adjust the box office revenue for inflation
        adjusted_revenue = adjust_for_inflation(release_year, df_movie_treated.iloc[i]['Movie box office revenue'], inflation_data)
        
        # Update the DataFrame with the adjusted revenue using iloc
        df_movie_treated.iloc[i, df_movie_treated.columns.get_loc('Movie box office revenue')] = adjusted_revenue
 
df_movie_treated.head(10)
#test = adjust_for_inflation(2023,1,inflation_data)
#test

Warning: No inflation data available for year 1897. Assuming 0% inflation.
Warning: No inflation data available for year 1898. Assuming 0% inflation.
Warning: No inflation data available for year 1899. Assuming 0% inflation.
Warning: No inflation data available for year 1900. Assuming 0% inflation.
Warning: No inflation data available for year 1901. Assuming 0% inflation.
Warning: No inflation data available for year 1902. Assuming 0% inflation.
Warning: No inflation data available for year 1903. Assuming 0% inflation.
Warning: No inflation data available for year 1904. Assuming 0% inflation.
Warning: No inflation data available for year 1905. Assuming 0% inflation.
Warning: No inflation data available for year 1906. Assuming 0% inflation.
Warning: No inflation data available for year 1907. Assuming 0% inflation.
Warning: No inflation data available for year 1908. Assuming 0% inflation.
Warning: No inflation data available for year 1909. Assuming 0% inflation.
Warning: No inflation data available for year 1910. Assuming 0% inflation.
Warning: No inflation data available for year 1911. Assuming 0% inflation.
Warning: No inflation data available for year 1912. Assuming 0% inflation.
Warning: No inflation data available for year 1913. Assuming 0% inflation.

,,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages,Movie countries,Movie genres
Wikipedia movie ID,Freebase movie ID,,,,,,,
975900,/m/03vyhn,Ghosts of Mars,2001-08-24,2.477118e+07,98.0,[English Language],[United States of America],"[Thriller, Science Fiction, Horror, Adventure,..."
3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,[English Language],[United States of America],"[Mystery, Biographical film, Drama, Crime Drama]"
28463795,/m/0crgdbh,Brun bitter,1988-01-01,NaN,83.0,[Norwegian Language],[Norway],"[Crime Fiction, Drama]"
9363483,/m/0285_cd,White Of The Eye,1987-01-01,NaN,110.0,[English Language],[United Kingdom],"[Thriller, Erotic thriller, Psychological thri..."
261236,/m/01mrr1,A Woman in Flames,1983-01-01,NaN,106.0,[German Language],[Germany],[Drama]
13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,"[Silent film, English Language]",[United States of America],"[Short Film, Silent film, Indie, Black-and-whi..."
18998739,/m/04jcqvw,The Sorcerer's Apprentice,2002-01-01,NaN,86.0,[English Language],[South Africa],"[Family Film, Fantasy, Adventure, World cinema]"
10408933,/m/02qc0j7,Alexander's Ragtime Band,1938-08-16,7.619573e+07,106.0,[English Language],[United States of America],"[Musical, Comedy, Black-and-white]"
9997961,/m/06_y2j7,Contigo y aquí,1974-01-01,NaN,NaN,[Spanish Language],[Argentina],"[Musical, Drama, Comedy]"
2345652,/m/075f66,City of the Dead,1960-01-01,NaN,76.0,[English Language],[United Kingdom],"[Horror, Supernatural]"

In [17]:

#wtf should we do with TXT files?
#look what data to clean up and what rows to remove






#other option ; 
#df_exploded = df.explode('Countries') or df['Countries'] = df['Countries'].str.split(', ')????????????
#check isunique for the indexes?


#add column character name, date of birth, gender, height,ethnicity, name, age at release?????????